---

- id: pdk_test_unit_pre_commit
  name: PDK Test Unit Runner
  description: Runs `pdk test unit` for puppet if files being commited are under a modules directory which has a spec directory.
  entry: pdk_test_unit_pre_commit.py
  language: python
  files: \.(pp|rb)$
